name: HTML Reporting Issue
description: Report issues with HTML report generation, styling, or content
title: "[report] "
labels: ["bug", "reporting"]
body:
  - type: markdown
    attributes:
      value: |
        ## Is This the Right Template?

        **Use this template if**:
        - HTML reports don't generate correctly
        - Report styling or layout is broken
        - Test results are missing or incorrectly displayed
        - Combined summary report has issues
        - `--minimal-reports` option causes problems

        **Use a DIFFERENT template if**:
        - Test execution fails → Use **"Bug Report"**
        - You want new report features → Use **"Feature Request"**

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: A clear description of the reporting issue.
      placeholder: Describe the issue...
    validations:
      required: true

  - type: dropdown
    id: report-type
    attributes:
      label: Report Type
      description: Which type of report is affected?
      options:
        - PyATS HTML Reports (individual test reports)
        - Robot Framework HTML Reports (Pabot/Robot output)
        - Combined Summary Report (combined_summary.html)
        - JSON Results (results.json)
        - All report types
    validations:
      required: true

  - type: dropdown
    id: report-mode
    attributes:
      label: Report Mode
      description: Which report generation mode are you using?
      options:
        - Standard (default, full reports)
        - Minimal (--minimal-reports flag)
        - Both (issue occurs in both modes)
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Network as Code (NaC) Architecture
      description: Which NaC architecture are you using? See https://netascode.cisco.com for supported architectures.
      options:
        - ACI (APIC)
        - NDO (Nexus Dashboard Orchestrator)
        - NDFC / VXLAN-EVPN (Nexus Dashboard Fabric Controller)
        - Catalyst SD-WAN (SDWAN Manager / vManage)
        - Catalyst Center (DNA Center)
        - ISE (Identity Services Engine)
        - FMC (Firepower Management Center)
        - Meraki (Cloud-managed)
        - NX-OS (Nexus Direct-to-Device)
        - IOS-XE (Direct-to-Device)
        - IOS-XR (Direct-to-Device)
        - Hyperfabric
        - Multiple architectures
        - N/A (architecture-independent)
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: "nac-test is supported on macOS and Linux only."
      options:
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "Specify your OS version"
      placeholder: "e.g., macOS Sonoma 14.2 or Ubuntu 22.04 LTS"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser Used to View Reports
      description: Which browser are you using to view the HTML reports?
      placeholder: "e.g., Chrome 120, Firefox 121, Safari 17"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Package Versions

        Please run the appropriate command for your OS and paste the output below.

        ---

        ### macOS Users:

        ```bash
        echo "=== NaC & Report Packages ===" && \
        (pip freeze 2>/dev/null || uv pip freeze 2>/dev/null) | grep -E "^(nac-|robot|pyats)"
        ```

        ---

        ### Linux Users:

        ```bash
        echo "=== NaC & Report Packages ===" && \
        (pip freeze 2>/dev/null || uv pip freeze 2>/dev/null) | grep -E "^(nac-|robot|pyats)"
        ```

  - type: textarea
    id: package-versions
    attributes:
      label: Package Versions Output
      description: Paste the output from the command above.
      render: text
    validations:
      required: true

  - type: textarea
    id: command-used
    attributes:
      label: Command Used
      description: The exact nac-test command you ran.
      render: bash
      placeholder: "nac-test --data ./data --templates ./tests --output ./results"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What the report should look like or contain.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What the report actually looks like or contains.
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If the issue is visual, please drag and drop a screenshot here.
    validations:
      required: false

  - type: input
    id: report-path
    attributes:
      label: Report File Location
      description: Path to the generated report file(s).
      placeholder: "./output/pyats_results/combined_summary.html"
    validations:
      required: false

  - type: textarea
    id: report-snippet
    attributes:
      label: Report Content Sample
      description: If applicable, share a snippet of the report HTML showing the issue (sanitize sensitive data!).
      render: html
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        - Does this happen for all tests or specific test types?
        - Did report generation work in a previous version?
        - Any console errors in the browser when viewing?
    validations:
      required: false
