name: How-To / Usage Question
description: Ask a question about how to use nac-test
title: "[question] "
labels: ["question"]
body:
  - type: checkboxes
    id: before-you-ask
    attributes:
      label: Before You Ask
      description: Please confirm you've checked these resources.
      options:
        - label: I have read the [Network as Code (NaC) Documentation](https://netascode.cisco.com/)
          required: true
        - label: I have checked the nac-test README
          required: true
        - label: I have searched existing issues for similar questions
          required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Clearly describe what you're trying to accomplish and where you're stuck.
      placeholder: "I'm trying to run D2D tests against my SD-WAN edge devices, but I'm not sure how to configure..."
    validations:
      required: true

  - type: textarea
    id: what-youve-tried
    attributes:
      label: What You've Tried
      description: List the approaches you've already attempted.
      placeholder: |
        1. First I tried...
        2. Then I tried...
        3. I also looked at...
    validations:
      required: true

  - type: dropdown
    id: test-framework
    attributes:
      label: Test Framework
      description: Which test framework are you working with?
      options:
        - PyATS
        - Robot Framework
        - Both
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: NaC Architecture
      description: Which NaC architecture are you working with? See https://netascode.cisco.com for supported architectures.
      options:
        - ACI (APIC)
        - NDO (Nexus Dashboard Orchestrator)
        - NDFC / VXLAN-EVPN (Nexus Dashboard Fabric Controller)
        - Catalyst SD-WAN (SDWAN Manager / vManage)
        - Catalyst Center (DNA Center)
        - ISE (Identity Services Engine)
        - FMC (Firepower Management Center)
        - Meraki (Cloud-managed)
        - NX-OS (Nexus Direct-to-Device)
        - IOS-XE (Direct-to-Device)
        - IOS-XR (Direct-to-Device)
        - Hyperfabric
        - Not sure / Multiple
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: "nac-test is supported on macOS and Linux only."
      options:
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "Specify your OS version"
      placeholder: "e.g., macOS Sonoma 14.2 or Ubuntu 22.04 LTS"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Package Versions

        Please run the appropriate command for your OS and paste the output below.

        ---

        ### macOS Users:

        ```bash
        (pip freeze 2>/dev/null || uv pip freeze 2>/dev/null) | grep -E "^nac-"
        ```

        ---

        ### Linux Users:

        ```bash
        (pip freeze 2>/dev/null || uv pip freeze 2>/dev/null) | grep -E "^nac-"
        ```

  - type: textarea
    id: package-versions
    attributes:
      label: Package Versions Output
      description: Paste the output from the command above.
      render: text
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command You're Running
      description: The nac-test command you're trying to run.
      render: bash
      placeholder: "nac-test --data ./data --templates ./tests --output ./results"
    validations:
      required: false

  - type: textarea
    id: data-model
    attributes:
      label: Data Model Snippet (if relevant)
      description: Relevant YAML snippet (sanitize sensitive data!).
      render: yaml
    validations:
      required: false

  - type: textarea
    id: test-file
    attributes:
      label: Test File Snippet (if relevant)
      description: Relevant test code snippet.
      render: python
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages (if any)
      description: If you're getting errors, include them here.
      render: text
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Project Directory Structure

        Showing your project structure helps us understand your setup and provide better guidance.

        **If you have `tree` installed:**

        ```bash
        tree -I '__pycache__|.venv|venv|site-packages|*.pyc|.git' --dirsfirst -L 3
        ```

        **If you don't have `tree`:**

        ```bash
        find . -type d \( -name __pycache__ -o -name .venv -o -name venv -o -name .git \) -prune -o -type f -print | head -50
        ```

  - type: textarea
    id: directory-structure
    attributes:
      label: Project Directory Structure (Optional)
      description: Paste the output from the tree command above (or describe your directory layout).
      render: text
      placeholder: |
        .
        ├── data/
        │   ├── defaults.yaml
        │   └── site1.yaml
        ├── tests/
        │   ├── verify_bgp.py
        │   └── d2d/
        │       └── verify_interfaces.py
        └── nac-test-results/
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help us understand your question.
    validations:
      required: false
